config status 'status'

config config 'config'
	option 'init' '1'
	option 'enabled' '0'
	option 'profile' 'mixin:mixin'
	option 'start_delay' '0'
	option 'test_profile' '1'

config procd 'procd'
	option 'rlimit_nofile_soft' '65536'
	option 'rlimit_nofile_hard' '65536'

config mixin 'mixin'
	option 'log_level' 'warning'
	option 'mode' 'rule'
	option 'ipv6' '1'
	option 'tproxy_port' '7892'
	option 'mixed_port' '7890'
	option 'api_listen' '[::]:9090'
	option 'ui_path' 'ui'
	option 'allow_lan' '1'

config proxy 'proxy'
	option 'enabled' '1'
	option 'ipv4_proxy' '1'
	option 'ipv6_proxy' '1'
	option 'ipv4_dns_hijack' '1'
	option 'ipv6_dns_hijack' '1'
	option 'tcp_mode' 'tproxy'
	option 'udp_mode' 'tproxy'

config routing 'routing'
	option 'tproxy_fw_mark' '0x80'
	option 'tproxy_fw_mask' '0xFF'
	option 'tproxy_rule_pref' '1024'
	option 'tproxy_route_table' '80'
